# Generated by Django 5.1.3 on 2024-11-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_id_alter_customuser_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='custom_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
