# Generated by Django 4.2.1 on 2024-11-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_key', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='face_key',
        ),
        migrations.DeleteModel(
            name='FaceKey',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
